[2021-11-16 11:56:38,914] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ml_pipeline.get_data scheduled__2021-11-15T00:06:00+00:00 [queued]>
[2021-11-16 11:56:38,923] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ml_pipeline.get_data scheduled__2021-11-15T00:06:00+00:00 [queued]>
[2021-11-16 11:56:38,923] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-16 11:56:38,923] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-16 11:56:38,924] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-16 11:56:39,006] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): get_data> on 2021-11-15 00:06:00+00:00
[2021-11-16 11:56:39,010] {standard_task_runner.py:52} INFO - Started process 13466 to run task
[2021-11-16 11:56:39,015] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'ml_pipeline', 'get_data', 'scheduled__2021-11-15T00:06:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/ml_dag.py', '--cfg-path', '/tmp/tmpo859z1rg', '--error-file', '/tmp/tmpf4912g83']
[2021-11-16 11:56:39,016] {standard_task_runner.py:77} INFO - Job 19: Subtask get_data
[2021-11-16 11:56:39,135] {logging_mixin.py:109} INFO - Running <TaskInstance: ml_pipeline.get_data scheduled__2021-11-15T00:06:00+00:00 [running]> on host ana-X550CA
[2021-11-16 11:56:39,326] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=plbalmeida
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2021-11-15T00:06:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-15T00:06:00+00:00
[2021-11-16 11:56:39,327] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-16 11:56:39,327] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/ana/Documentos/airflowML/src/data/make_dataset.py']
[2021-11-16 11:56:39,337] {subprocess.py:85} INFO - Output:
[2021-11-16 11:56:39,849] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-16 11:56:39,957] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=get_data, execution_date=20211115T000600, start_date=20211116T145638, end_date=20211116T145639
[2021-11-16 11:56:40,068] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-16 11:56:40,170] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
