[2021-11-16 11:57:08,333] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ml_pipeline.get_data manual__2021-11-16T14:56:54.423722+00:00 [queued]>
[2021-11-16 11:57:08,346] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ml_pipeline.get_data manual__2021-11-16T14:56:54.423722+00:00 [queued]>
[2021-11-16 11:57:08,346] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-16 11:57:08,346] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-16 11:57:08,346] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-16 11:57:08,443] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): get_data> on 2021-11-16 14:56:54.423722+00:00
[2021-11-16 11:57:08,446] {standard_task_runner.py:52} INFO - Started process 13552 to run task
[2021-11-16 11:57:08,451] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'ml_pipeline', 'get_data', 'manual__2021-11-16T14:56:54.423722+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/ml_dag.py', '--cfg-path', '/tmp/tmpaz2xw_cv', '--error-file', '/tmp/tmph_ackbv6']
[2021-11-16 11:57:08,452] {standard_task_runner.py:77} INFO - Job 26: Subtask get_data
[2021-11-16 11:57:08,579] {logging_mixin.py:109} INFO - Running <TaskInstance: ml_pipeline.get_data manual__2021-11-16T14:56:54.423722+00:00 [running]> on host ana-X550CA
[2021-11-16 11:57:08,770] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=plbalmeida
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2021-11-16T14:56:54.423722+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-16T14:56:54.423722+00:00
[2021-11-16 11:57:08,771] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-16 11:57:08,771] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/ana/Documentos/airflowML/src/data/make_dataset.py']
[2021-11-16 11:57:08,781] {subprocess.py:85} INFO - Output:
[2021-11-16 11:57:09,311] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-16 11:57:09,405] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=get_data, execution_date=20211116T145654, start_date=20211116T145708, end_date=20211116T145709
[2021-11-16 11:57:09,505] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-16 11:57:09,593] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
