[2021-11-16 11:59:37,780] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ml_pipeline.get_data manual__2021-11-16T14:59:26.350719+00:00 [queued]>
[2021-11-16 11:59:37,792] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ml_pipeline.get_data manual__2021-11-16T14:59:26.350719+00:00 [queued]>
[2021-11-16 11:59:37,792] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-16 11:59:37,792] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-16 11:59:37,792] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-16 11:59:37,964] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): get_data> on 2021-11-16 14:59:26.350719+00:00
[2021-11-16 11:59:37,967] {standard_task_runner.py:52} INFO - Started process 13876 to run task
[2021-11-16 11:59:37,970] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'ml_pipeline', 'get_data', 'manual__2021-11-16T14:59:26.350719+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/ml_dag.py', '--cfg-path', '/tmp/tmpvddgyo22', '--error-file', '/tmp/tmpfy8yc5us']
[2021-11-16 11:59:37,971] {standard_task_runner.py:77} INFO - Job 40: Subtask get_data
[2021-11-16 11:59:38,066] {logging_mixin.py:109} INFO - Running <TaskInstance: ml_pipeline.get_data manual__2021-11-16T14:59:26.350719+00:00 [running]> on host ana-X550CA
[2021-11-16 11:59:38,255] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=plbalmeida
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2021-11-16T14:59:26.350719+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-16T14:59:26.350719+00:00
[2021-11-16 11:59:38,256] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-16 11:59:38,256] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/ana/Documentos/airflowML/src/data/make_dataset.py']
[2021-11-16 11:59:38,264] {subprocess.py:85} INFO - Output:
[2021-11-16 11:59:38,792] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-16 11:59:38,873] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=get_data, execution_date=20211116T145926, start_date=20211116T145937, end_date=20211116T145938
[2021-11-16 11:59:38,985] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-16 11:59:39,029] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
