[2021-11-16 11:56:56,312] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ml_pipeline.get_data scheduled__2021-11-15T00:12:00+00:00 [queued]>
[2021-11-16 11:56:56,319] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ml_pipeline.get_data scheduled__2021-11-15T00:12:00+00:00 [queued]>
[2021-11-16 11:56:56,319] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-16 11:56:56,319] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-16 11:56:56,319] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-16 11:56:56,466] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): get_data> on 2021-11-15 00:12:00+00:00
[2021-11-16 11:56:56,469] {standard_task_runner.py:52} INFO - Started process 13523 to run task
[2021-11-16 11:56:56,474] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'ml_pipeline', 'get_data', 'scheduled__2021-11-15T00:12:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/ml_dag.py', '--cfg-path', '/tmp/tmp09xqys_0', '--error-file', '/tmp/tmpytkmrdj8']
[2021-11-16 11:56:56,476] {standard_task_runner.py:77} INFO - Job 23: Subtask get_data
[2021-11-16 11:56:56,607] {logging_mixin.py:109} INFO - Running <TaskInstance: ml_pipeline.get_data scheduled__2021-11-15T00:12:00+00:00 [running]> on host ana-X550CA
[2021-11-16 11:56:56,779] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=plbalmeida
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2021-11-15T00:12:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-15T00:12:00+00:00
[2021-11-16 11:56:56,780] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-16 11:56:56,780] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/ana/Documentos/airflowML/src/data/make_dataset.py']
[2021-11-16 11:56:56,789] {subprocess.py:85} INFO - Output:
[2021-11-16 11:56:57,347] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-16 11:56:57,455] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=get_data, execution_date=20211115T001200, start_date=20211116T145656, end_date=20211116T145657
[2021-11-16 11:56:57,568] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-16 11:56:57,672] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
