[2021-11-16 12:02:47,074] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ml_pipeline.get_data manual__2021-11-16T15:02:43.789671+00:00 [queued]>
[2021-11-16 12:02:47,081] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ml_pipeline.get_data manual__2021-11-16T15:02:43.789671+00:00 [queued]>
[2021-11-16 12:02:47,082] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-16 12:02:47,082] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-16 12:02:47,082] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-16 12:02:47,156] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): get_data> on 2021-11-16 15:02:43.789671+00:00
[2021-11-16 12:02:47,158] {standard_task_runner.py:52} INFO - Started process 14195 to run task
[2021-11-16 12:02:47,163] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'ml_pipeline', 'get_data', 'manual__2021-11-16T15:02:43.789671+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/ml_dag.py', '--cfg-path', '/tmp/tmp6567ej7r', '--error-file', '/tmp/tmpyr18pv42']
[2021-11-16 12:02:47,165] {standard_task_runner.py:77} INFO - Job 42: Subtask get_data
[2021-11-16 12:02:47,292] {logging_mixin.py:109} INFO - Running <TaskInstance: ml_pipeline.get_data manual__2021-11-16T15:02:43.789671+00:00 [running]> on host ana-X550CA
[2021-11-16 12:02:47,503] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=plbalmeida
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2021-11-16T15:02:43.789671+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-16T15:02:43.789671+00:00
[2021-11-16 12:02:47,503] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-16 12:02:47,504] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/ana/Documentos/airflowML/src/data/make_dataset.py']
[2021-11-16 12:02:47,514] {subprocess.py:85} INFO - Output:
[2021-11-16 12:02:48,329] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-16 12:02:48,788] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=get_data, execution_date=20211116T150243, start_date=20211116T150247, end_date=20211116T150248
[2021-11-16 12:02:48,876] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-16 12:02:48,959] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
